### ISSUE TITLE
Sim is slowed down when dragging the point in the graph area.

### ISSUE THREAD

**Issue by memo330179** [phetsims/curve-fitting#103]
When the curve updates it goes through every point between the x-axis.

``` javascript
for ( x = xMin; x < xMax; x += PLOT_STEP ) {
            curveShape.lineTo( x, curve.getYValueAt( x ) );
          }
          // we want to make sure to end on xMax, irrespective of the value of PLOT_STEP
          curveShape.lineTo( xMax, curve.getYValueAt( xMax ) );
```

This makes the drawing of the curve very slow in the iPad2 when moving a point around, redrawing the curve repeatedly. As soon as a point enters the graph area, we start calculating the fit and redrawing the curve many times.

**Comment by veillette** [comment]
@memo330179 : Jonathon Olson outlined a procedure to plot a quadratic curve using a Bezier.
You can find the details in  https://github.com/phetsims/graphing-quadratics/issues/1

It should address the performance problem since it replaces hundreds of short linear segments by one Bezier. 

The general approach can be generalized to Cubic polynomial.

**Comment by veillette** [comment]
it would be worth checking if this change improve  significantly the rendering of the curve on the iPad.

**Comment by veillette** [comment]
The cubic Bezier algorithm has not been implemented yet. We should wait if the quadratic Bezier improves the performance before tackling the cubic Bezier.

**Comment by veillette** [comment]
The simulation was tested on an iPad 2 and it does resolve the problem.  so closing
