### ISSUE TITLE
Allow uncertainty bars to be expanded up or down from zero position

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/curve-fitting#127]
Currently if the uncertainty is set to zero, the uncertainty can only be expanded "upwards" - we should make it symmetric so the user can either pull up or down to expand from zero, since once the bars are expanded, the user can adjust using either the upper or lower bar.

**Comment by SaurabhTotey** [comment]
I have changed the dragging behaviour to now set the delta to the absolute distance of the mouse from the point's y center. This means that both error bar portions can be dragged in both directions at all times. This makes it slightly harder to get a delta of 0 (because there is no automatic stopping) and it gives the visual illusion that the error bars switch places.

I think this feels a little weird, but is probably better behaviour than what was happening before. Before, the top error bar was getting layered on top and was getting the drag events before the bottom error bar. As such, at a delta of 0, only the top error bar was draggable, which is why the delta was only allowed to expand back up after collapsed. Adding an exception to the top error bar to only allow it to get dragged downwards below the point's y center when the delta is effectively 0 seems like it would be a much harder solution to implement.

Assigning to @amanda-phet to see whether the current behaviour is acceptable.

**Comment by amanda-phet** [comment]
This certainly solves the original issue, but I don't think we can go this route. It is just too difficult to get to 0. 

I would prefer what we had before over this. If you have another idea it might be worth trying out, though. Feel free to slack me to bounce ideas around.

**Comment by SaurabhTotey** [comment]
Ok, I will reassign this to myself for the time being and revert the changes of ae8370f. I'll try and revisit this again at a later point in time if I have thought of anything else for this issue.

**Comment by SaurabhTotey** [comment]
I have spent a bunch of time on this, and I have implemented a solution on master that might feel better. I added flags so that when the delta is 0, there is a special exception to allow the top bar to be dragged down as if it were the bottom bar. Once the top bar decides whether it will behave as a top bar or bottom bar, it sticks to that behaviour until the end of the drag. This solution required a lot of new logic, so I am unsure if I have tested all the edge cases (it may be buggy).

Assigning to @amanda-phet to review and see whether I should continue down this path for behaviour.

**Comment by amanda-phet** [comment]
I like it a lot! I didn't look for bugs but the behavior seems really smooth to me.

**Comment by SaurabhTotey** [comment]
Thanks! Since posting the original comment, I have tested the behaviour, and I haven't yet found a bug. I'll close this issue for right now, and if bugs are found with this during testing, this issue can be reopened or a new issue can be opened.
