### ISSUE TITLE
shrink slider thumbs

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/curve-fitting#128]
Make them slightly smaller so that you can see the 0 mark, but keep the touch areas as large as possible. Maybe make the thumbs a tiny bit shorter in addition to scaling them.

**Comment by SaurabhTotey** [comment]
I have changed the slider thumbs so that they are less "heavy", but still have the same touch areas as before. They might appear to be a little bit too thin now. Also the 0 value only barely peeks out from below the sliders. Below are images of what this looks like for right now.

<img width="199" alt="sliderswithoutpointerareas" src="https://user-images.githubusercontent.com/22577113/61140674-1584a480-a489-11e9-9158-a305abb50df1.png">
<img width="199" alt="sliderswithpointerareas" src="https://user-images.githubusercontent.com/22577113/61140673-13bae100-a489-11e9-8e47-07eb65a4ac60.png">

Assigning to @amanda-phet to get feedback on what sliders should look like/where to go from here.

**Comment by amanda-phet** [comment]
yeah, can you make them just a little bit taller? 

I'm OK with the amount of the 0 line that is visible. You can always look at the equation for values (which is exactly what I do) but this is just a little more helpful.

**Comment by SaurabhTotey** [comment]
Ok, sounds good. I have increased the thumbs from height 8 to 10. Here is what it looks like now. I can increase the height even more if needed.
<img width="208" alt="tallerthumbs" src="https://user-images.githubusercontent.com/22577113/61144579-75cc1400-a492-11e9-8ca6-260730685035.png">

**Comment by amanda-phet** [comment]
I like them! These look great to me.
