### ISSUE TITLE
Equation AccordionBox can prevent points from being dragged

### ISSUE THREAD

**Issue by SaurabhTotey** [phetsims/curve-fitting#131]
It is possible to drag the point to a place where it is completely covered by the expand/collapse accordion button and cannot be dragged out.
<img width="199" alt="accordionboxcoveringpoint" src="https://user-images.githubusercontent.com/22577113/61411082-c84a6d80-a8a2-11e9-8d2c-119ce9f4b1ca.png">

I can either increase the point touch areas or decrease the touch areas for the expand/collapse button in the equation accordion box.

Assigning to @amanda-phet to choose which way would be most ideal for solving this issue.

**Comment by amanda-phet** [comment]
This seems like an annoying situation to be in, especially if someone doesn't realize the point is there. You *can* hide the curve to grab the point, but that doesn't seem like a great solution. I hesitate to change the size of the touch areas because otherwise they are all working nicely. 

I guess I am leaning toward making the expandCollapseButton touch area smaller, since that is a simpler solution. We already fine-tuned the point touch areas so I don't want to mess with those any more! 

@ariel-phet any thoughts?

**Comment by ariel-phet** [comment]
@amanda-phet @SaurabhTotey in some sims we have had a "bump out" rule. If you place an object somewhere undesirable, it "bumps" out of that position. or you could restrict the point to not go under the expand/collapse button. Perhaps ping the dev-channel for some examples of where this kind of solution has been implemented. It seems placing a point here is not very useful anyhow, and should be avoided.

**Comment by SaurabhTotey** [comment]
I made some behaviour that bumps the points out if they are under the expand/collapse button. The points get pushed until their center is outside of certain bounds (the bounds right now are set to be the same as the button's bounds). I can expand the bounds where the points get pushed so that they get pushed out further. Assigning to @amanda-phet to review.

**Comment by amanda-phet** [comment]
I was able to test this and I don't think the bump is big enough because I still have a hard time grabbing the point. Can you increase it slightly?

**Comment by SaurabhTotey** [comment]
I have expanded the push bounds so that the center of a point must be at outside an area that is the button's area dilated in each direction by 0.55 in terms of model/graph coordinates.

**Comment by amanda-phet** [comment]
That looks great to me! Thanks!
