### ISSUE TITLE
Curve fitting type is not preserved

### ISSUE THREAD

**Issue by bryo5363** [phetsims/curve-fitting#15]
To elaborate on @phet-steele previous issue: 

1. open sim
2. click curve, throw on some data points
3. click quadratic
4. adjust fit
5. click cubic

note that the cubic selection now has a quadratic curve

**Comment by bryo5363** [comment]
along with this, once the user clicks best fit and then adjust on a certain curve type (cubic for best results) the best fit line is preserved but once the user interacts with the sliders, the equation rapidly changes.

**Comment by phet-steele** [comment]
Furthermore, using multitouch one can be sliding the bar to adjust "a" on cubic but then, while still dragging the slider, use another finger to switch to quadratic and still be in control of the "a" slider. This retains the cubic appearance of the graph even though quadratic is selected.

**Comment by amanda-phet** [comment]
See #13 for more details about this bug.

**Comment by andrey-zelenkov** [comment]
Fixed preserving of curve type. Reassign to @bryo5363 for verification.

**Comment by amanda-phet** [comment]
@bryo5363 can you please check this out?

**Comment by phet-steele** [comment]
I'm looking at this while checking #13. The original procedure in the first comment is fixed. Switching between curve types while Adjustable fit is selected will return the coefficient values to a default (I still think it would be great to save the fits so the user can return back to one they already made instead of having to remake it).
However, curve type is not preserved in a new case:
1. Click curve and place some data points.
2. Choose cubic
3. Then Adjustable fit
4. Mess with the sliders
5. Go back to best fit
6. Choose quadratic
7. Adjustable fit. You may have to move some sliders to see your graph more clearly, but it is still cubic in shape.

**Comment by andrey-zelenkov** [comment]
Fixed curve fitting type preserving. Reassign to @phet-steele for verification.

**Comment by phet-steele** [comment]
Fixed. Making a new issue about the sliders returning to default and one about the multitouch problem where you can move the "a" slider while viewing a quadratic curve.
