### ISSUE TITLE
Model and implementation-notes documentation

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#71]
Noted in the checklist for https://github.com/phetsims/curve-fitting/issues/31 is the lack of doc/model.md and doc/implementation-notes.md. Could these be filled out with top-level model/implementation note documentation?

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
Added model.md and implementation-notes.md. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Thanks.

**Comment by pixelzoom** [comment]
@veillette @jonathanolson @SaurabhTotey  FYI, I found both of these files to be a bit "sparse" during final code review #143.   I created #144 to get lead design sign-off on model.md, because it looks like that didn't happen.  And I checked off implementation-notes.md in the review list, even though it didn't give me any "overview" of things like model-view transform, lifetime of Properties and other observables, and other stuff that I'd expect to find here.
