### ISSUE TITLE
fix alignment of equation terms above sliders

### ISSUE THREAD

**Issue by veillette** [phetsims/curve-fitting#80]
The process of making the strings translatable broke the alignment of the equation with the slider

**Comment by pixelzoom** [comment]
This is presumably referring to the sliders that appear when "Adjustable fix" is selected, and the terms that each of those sliders is associated with.

**Comment by pixelzoom** [comment]
Assigning to @memo330179, since this is one of the "3 specific issues" to work on first.

**Comment by memo330179** [comment]
I need some clarification on this issue. I am not sure what the alignment issue is. My first instinct says the sliders all should be in the center, but I am not sure.

**Comment by pixelzoom** [comment]
The sliders should be positioned below their respective terms in the equation.  Here's a mockup from the design document. Note how the slider for 'a' is centered below the 'a' in the equation (and similarly for other terms).

![screenshot_63](https://cloud.githubusercontent.com/assets/3046552/20107375/956bde7a-a595-11e6-80e2-94f39feadde9.png)

**Comment by SaurabhTotey** [comment]
I have made a few small commits to try and reduce this issue. The sliders are right now slightly better aligned under the coefficients, but it still isn't quite perfect. I have spent a lot of time trying to get perfect alignment (using things like `.centerX`) to no avail, so I have instead used an HStrut and a modification of slider dimensions as a stopgap. Below are a few pictures of how it looks as of this current moment.

<img width="222" alt="linear" src="https://user-images.githubusercontent.com/22577113/58830051-a6549e80-8606-11e9-9bcc-032ebbb3733d.png">

<img width="222" alt="quadratic" src="https://user-images.githubusercontent.com/22577113/58830065-ac4a7f80-8606-11e9-8477-27c43feb96e4.png">

<img width="222" alt="cubic" src="https://user-images.githubusercontent.com/22577113/58830076-b10f3380-8606-11e9-8d82-9e4f6f581322.png">

**Comment by pixelzoom** [comment]
Trying to eyeball the slider locations is problematic, especially since font sizes vary on browsers, and translated symbols will change term width.  If you want to precisely position the sliders under terms, you might try adding methods to the equation that allow you to get the position of each term.  That will give you the information needed to position the sliders.  You may need to transform the term position (using Node's coordinate transform methods, e.g. , `parentToGlobalPoint`, `globalToParentPoint`) to put it in the slider's coordinate frame.   Let me know if I can help.

**Comment by SaurabhTotey** [comment]
Thanks for the offer for help! Eventually, I was able to figure out why my previous attempts at setting `centerX` didn't work. After a few hours of trying to figure out why my solutions weren't working, I figured out that I was having issues with HBox and VBox ignoring the fact that I was setting a new `centerX`. I just fixed this by replacing the usages of HBox and VBox with Node and spacing elements relative to each other. Now the sliders are exactly under coefficients. I have included images below.

<img width="230" alt="Linear" src="https://user-images.githubusercontent.com/22577113/58913273-15022c80-86d9-11e9-8d44-ef564c99c283.png">

<img width="230" alt="Quadratic" src="https://user-images.githubusercontent.com/22577113/58913286-1b90a400-86d9-11e9-9424-3eb332acc253.png">

<img width="230" alt="Cubic" src="https://user-images.githubusercontent.com/22577113/58913290-20edee80-86d9-11e9-9aa2-8908cf74ab7c.png">

It seems like the `c` and `d` sliders are closer to each other than other sliders because the linear term of the equation doesn't have an exponent to provide it extra spacing. I am wondering if this correct/desired behaviour, or whether the equation should have different spacing. Regardless, the sliders now align exactly under the coefficients.

**Comment by pixelzoom** [comment]
@SaurabhTotey wrote:
> ... Now the sliders are exactly under coefficients. 

Nicely done!

> ... I am wondering if this correct/desired behaviour, or whether the equation should have different spacing.

In Graphing Quadratics, the difference in horizontal space between sliders was OK, see screenshot below.  But you should check with @amanda-phet, since this sim may have requirements that I'm not aware of.

<img width="335" alt="screenshot_1230" src="https://user-images.githubusercontent.com/3046552/58914276-54ca1380-86db-11e9-9d94-6fe31c2a51f0.png">

**Comment by SaurabhTotey** [comment]
Assigning to @amanda-phet to review and either give feedback or sign off. The feedback on this issue will potentially affect how I will need to attempt #72.

**Comment by amanda-phet** [comment]
Since these sliders are much closer than the ones in GQ, I have a bit more hesitation. c and d are just really close and it seems a problematic from a touch perspective and a little unnecessary. I would prefer if they were more evenly spaced, even if they aren't directly under the coefficients (sorry!). The spacing between a, b, and c looks good, so maybe just apply that to all of the sliders.

**Comment by SaurabhTotey** [comment]
Now in master, the sliders are placed relative to each other and the left edge and have an even spacing. This comes at the expense that the sliders aren't guaranteed to be _exactly_ under the coefficients, which I don't think should be a huge issue. This is what it looks like now.

<img width="224" alt="sliders" src="https://user-images.githubusercontent.com/22577113/59536671-7da79100-8eb1-11e9-8957-16d1b84cebbd.png">

**Comment by amanda-phet** [comment]
Checked on master and they look great to me! Thanks for making that change.
