### ISSUE TITLE
address i18n issues with text containing math symbols

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#91]
See https://github.com/phetsims/curve-fitting/issues/74#issuecomment-237897994 and https://github.com/phetsims/scenery-phet/issues/251.

This concerns these 2 lines of text, in ReducedChiSquaredStatisticDialog:

![screenshot_76](https://cloud.githubusercontent.com/assets/3046552/17444988/07f463c6-5b00-11e6-8f6e-57992aa07e67.png)

Because the math symbols (f, N) must use a different font than the rest of the text, these lines consist of multiple Text nodes, with a fixed layout.  The translator has no control over this aspect of the layout.  This may impact RTL languages.

**Comment by SaurabhTotey** [comment]
Assigning to @amanda-phet to see whether this issue can be deferred or not. Ideally, it would be nice to have something like `TextWithEmbeddedNodes` to solve this issue, as described in phetsims/scenery-phet#251, but it seems like that class does not yet exist and it will probably take a while.

**Comment by amanda-phet** [comment]
I do agree with @pixelzoom that this might cause problems. What will it look like with a RTL locale? Can you direct me to the query parameter so I can see?

**Comment by SaurabhTotey** [comment]
Pasting a conversation with Chris from 6/10/19:

> Saurabh Totey [12:08 PM]
> Hey Chris,
> I was looking through https://github.com/phetsims/curve-fitting/issues/91 and I saw that you mentioned you had a temporary workaround for this in curve-fitting in https://github.com/phetsims/scenery-phet/issues/251#issuecomment-240817075. As such, I was wondering whether this issue in curve-fitting is still something I should work on, or if it is something I can leave.
> 
> Chris Malley [12:13 PM]
> Checking…
> 
> Chris Malley [12:19 PM]
> Looks like I addressed the font issue in https://github.com/phetsims/curve-fitting/issues/74#issuecomment-237897994.  But the layout issue has not been addressed.  My feeling is that we could defer the layout issue for now.  But probably best to ask Amanda.

It seems like using an RTL locale definitely causes problems. I haven't been able to find an explicit RTL query parameter, but I did find a query parameter called `locale`, where if I add `locale=ur` (Urdu seems to be an RTL locale) to the sim, the dialog text breaks badly. The text is still in English, but the layout of symbols relative to the text is nonsensical.

<img width="651" alt="rtl dialog" src="https://user-images.githubusercontent.com/22577113/59372495-e0a7f500-8d04-11e9-8449-e714175e8089.png">

However, because there are multiple text nodes embedded together, solving this issue would be difficult. There needs to be multiple text nodes because of the separate fonts of parts of the text, so laying out the nodes correctly for RTL languages would be hard to do without some tool like `TextWithEmbeddedNodes`.

**Comment by SaurabhTotey** [comment]
I'm reassigning this issue to myself because I believe I may be able to implement a workaround for how to make these strings more translate-friendly using string templates and RichText font-family funcitonality.

**Comment by SaurabhTotey** [comment]
Using string patterns and StringUtils.fillIn, I believe that the strings in this dialog are now fully translatable, even for RTL languages. I have included the string patterns below just in case.

```
"pattern.fEqualsNumberOfParameters": {
  "value": "{{fSymbol}} = number of parameters in fit (e.g. {{fSymbol}} = 4, for a cubic fit)"
},
"pattern.nEqualsNumberOfDataPoints": {
  "value": "{{nSymbol}} = number of data points"
},
```

To allow for the use of math font, I use RichText formatting for the symbols that are passed in. Because I believe this issue is solved, I will close this issue.
