### ISSUE TITLE
location of y-axis tick marks

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#93]
At some point, the y axis tick marks moved from +5 and -5 to +6.3 and -3.7.  This doesn't seem like it was an intentional change. 

I isolated the change to b07d5c256053a8cce0955041474b934606f4a982, by @memo330179 on 7/8/16, well before I started cleaning up this sim. 

Since then, the y axis ticks have continued to migrate. As of master 4cc9cea05f33bef3322ae99fe869630094642bc1, they are at +5.7 and -4.3.

**Comment by pixelzoom** [comment]
Definitely a bug, see https://github.com/phetsims/curve-fitting/issues/92#issuecomment-238316257.

**Comment by veillette** [comment]
The ticks are now in the correct position. However, they should be refactored because (1) they are based on the view position rather than the model.
As of right now they are set to appear 1/4 and 3/4 of the way of the graph.

In the long run, it would be better to have a tickMark factory that would generate tick marks at the specified location.

**Comment by SaurabhTotey** [comment]
From what I can parse from GraphAreaNode, it seems like the graph area is now consistently from -11 to 11 for both axes, and it seems like the ticks are now generated in a way that, at least to me, seems to make sense. The ticks are added based on model location, and transformed to view coordinates using a ModelViewTransform. The graph area and ticks both seem to be consistent, and I haven't seen them move or change locations. I believe that this issue is solved.
