### ISSUE TITLE
odd combination of Nodes in BucketAndGraphAreaNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#99]
BucketAndGraphAreaNode combines 3 UI components (bucket, graph and a control panel) in a bizarre manner that makes model-view transforms brittle and difficult to figure out.  Looks like this was done to facilitate dragging points from the bucket to the graph.  But there are much better ways to do this.  Recommended to separate these UI components and redesign this part of the user interface.

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/curve-fitting/issues/87

**Comment by veillette** [comment]
Digging into this, I found that at some point in the past , the data points where handle through a custom pixelToModel transformation. Hence, it was convenient to get all nodes that handles points in one node. Since the sim is now using a model view transform, this approach is no longer relevant.  The BucketAndGraphAreaNode was eliminated altogether.

The curveFittingScreenView is the parent graphAreaNode and EquationGraphPanelNode. All the other responsibilities for the bucket have been folded into the BucketNode .

**Comment by SaurabhTotey** [comment]
It seems like this issue is no longer relevant after BucketAndGraphAreaNode has been removed. Marking as ready for review.
